# Change these first
owner: GESISWTS  # Your GitHub username
repo: uptime # Your Github repository name

# Add your sites here
sites:
  - name: ZIS
    url: https://zis.gesis.org
  - name: x-science
    url: https://www.x-science.org/xscience/#!Home
  - name: x-econ.org
    url: https://x-econ.org/xecon/#!Home
  - name: GESIS Login
    url: https://login.gesis.org
  - name: Data Sharing
    url: https://data.gesis.org/sharing/#!Home
  - name: qeditor - app
    url: https://multiweb.gesis.org/labs/apps/qeditor
  - name: qeditor
    url: https://multiweb.gesis.org/qeditor
  - name: GESIS Missy
    url: https://www.gesis.org/missy
  # HTTPS certificate expired?
  - name: leibnizopen
    url: http://www.leibnizopen.de/suche/handle/document/113707
  - name: DA-RA
    url: https://www.da-ra.de/dara/mydara
  - name: vocabularies
    url: https://vocabularies.cessda.eu
  - name: GESIS Notebooks
    url: https://notebooks.gesis.org
    assignees:
      - MridulS
  - name: GESIS Notebooks - BinderHub
    url: https://notebooks.gesis.org/binder
    assignees:
      - MridulS
  - name: GESIS Notebooks - Gallery
    url: https://notebooks.gesis.org/gallery/
    assignees:
      - MridulS
 # Hackish way to check the JSON fields
  - name: Persistent BinderHub - Health
    url: https://notebooks.gesis.org/services/binder/health
    __dangerous__body_degraded: '{"ok": true,'
    assignees:
      - MridulS
  - name: Persistent BinderHub - Docker
    url: https://notebooks.gesis.org/services/binder/health
    __dangerous__body_degraded: '{"service": "Docker registry", "ok": false}'
    assignees:
      - MridulS
  - name: Persistent BinderHub - Hub API
    url: https://notebooks.gesis.org/services/binder/health
    __dangerous__body_degraded: '{"service": "JupyterHub API", "ok": false}'
    assignees:
      - MridulS
  - name: BinderHub - Health
    url: https://notebooks.gesis.org/binder/health
    __dangerous__body_degraded: '{"ok": false,'
    assignees:
      - MridulS
  - name: BinderHub - Docker
    url: https://notebooks.gesis.org/binder/health
    __dangerous__body_degraded: '{"service": "Docker registry", "ok": false}'
    assignees:
      - MridulS
  - name: BinderHub - Hub API
    url: https://notebooks.gesis.org/binder/health
    __dangerous__body_degraded: '{"service": "JupyterHub API", "ok": false}'
    assignees:
      - MridulS

status-website:
  baseUrl: /uptime
  logoUrl: https://avatars3.githubusercontent.com/u/7595082?s=200&v=4
  name: "GESIS WTS Services"
  introMessage: "Status page tracking various projects and services run by the WTS department at GESIS."
  navbar:
    - title: Status
      href: /uptime
    - title: GitHub
      href: https://github.com/gesiswts/uptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
